### ISSUE TITLE
Not able to deploy with docker

### ISSUE THREAD

**Issue by bear2107** [brndnmtthws/labhub#93]
I updated the LabHub file  with my credentials and then did a docker build. It works fine but the moment i do docker run <image> it gives me the following error:
Warning: environment is 'production', but no `secret_key` is configured
thread 'main' panicked at 'Unable to open the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by bear2107** [comment]
where should i put it ? i modified Labhub variables. Is there anything else i need to do

**Comment by bear2107** [comment]
Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 4
    => secret key: generated
    => limits: forms = 32KiB
    => keep-alive: 5s
    => tls: disabled
✨ May your hopes and dreams become reality ✨
Loaded LabHub configuration values from LabHub.toml
thread 'main' panicked at 'Unable to open the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

I got this when deploying under dev mode. It loaded configuration values from LabHub.toml
